let div = document.createElement('div');
	div.classList.add("w-screen", "m-0", "bg-gray-800" , "shadow-lg","pb-3", "pt-2", "text-center");
		let a = document.createElement('a');
			a.href="https://www.youtube.com/watch?v=dQw4w9WgXcQ";
			a.classList.add("space-y-2", "float-left", "ml-4", "mt-3");
			let span1 = document.createElement('span');
				span1.classList.add("block","w-8" ,"h-1", "bg-blue-300");
			let span2 = document.createElement('span');
				span2.classList.add("block","w-8" ,"h-1", "bg-blue-300");
			let span3 = document.createElement('span');
				span3.classList.add("block","w-8" ,"h-1", "bg-blue-300");
			a.appendChild(span1);
			a.appendChild(span2);
			a.appendChild(span3);
		div.appendChild(a);
		let h1 = document.createElement('h1');
			h1.classList.add("text-5xl", "text-blue-300", "mr-12");
			h1.textContent="Wordle";
		div.appendChild(h1);
document.body.appendChild(div);