let div = document.createElement('div');
	div.classList.add("w-screen", "m-0", "bg-gray-800" , "shadow-lg","pb-3", "pt-2", "text-center");
		let a = document.createElement('a');
			a.href="https://www.youtube.com/watch?v=dQw4w9WgXcQ";
			a.classList.add("space-y-2", "float-left", "ml-4", "mt-3");
			let span1 = document.createElement('span');
				span1.classList.add("block","w-8" ,"h-1", "bg-blue-300");
			let span2 = document.createElement('span');
				span2.classList.add("block","w-8" ,"h-1", "bg-blue-300");
			let span3 = document.createElement('span');
				span3.classList.add("block","w-8" ,"h-1", "bg-blue-300");
			a.appendChild(span1);
			a.appendChild(span2);
			a.appendChild(span3);
		div.appendChild(a);
		let h1 = document.createElement('h1');
			h1.classList.add("text-5xl", "text-blue-300", "mr-12");
			h1.textContent="Wordle";
		div.appendChild(h1);
document.body.appendChild(div);
let div4 = document.createElement('div');
    div4.classList.add("container","mx-auto");
        let div2 = document.createElement('div');
            div2.classList.add("grid", "grid-cols-6", "gap-4", "text-center", "grid-rows-6","mywidth", "mx-auto", "border-4", "gap-x-5", "gap-y-5", "mt-36", "border-none","inputparent");
            for (let i =0;i<36;i++){
                let div3 = document.createElement('div');
                    div3.classList.add("bg-blue-300", "border-2", "border-gray-800", "h-16", "w-16");
                    div2.appendChild(div3);
            }
        div4.appendChild(div2);
document.body.appendChild(div4);
